import os
import requests
import yaml
import tempfile
from pathlib import Path

class PaperCollector:
    def __init__(self, output_dir="data/raw/papers"):
        self.output_dir = output_dir
        base_dir = Path(__file__).parent
        config_path = base_dir / "config_sources.yaml"
        if config_path.exists():
            with open(config_path, "r", encoding="utf-8") as f:
                self.config = yaml.safe_load(f).get("papers", {})
        else:
            self.config = {}

    def collect(self):
        """Query arXiv for Karpathy's papers, or use mock if query fails"""
        os.makedirs(self.output_dir, exist_ok=True)
        query = self.config.get("query", 'au:"Andrej Karpathy"')
        
        success = False
        try:
            import arxiv
            print(f"Querying arXiv for: {query}...")
            client = arxiv.Client()
            search = arxiv.Search(query=query, max_results=5)
            results = list(client.results(search))
            
            if results:
                for paper in results:
                    pdf_url = paper.pdf_url
                    paper_id = paper.entry_id.split('/abs/')[-1]
                    try:
                        self._download_and_extract(
                            pdf_url, 
                            paper_id, 
                            paper.title, 
                            paper.published
                        )
                        success = True
                    except Exception as ex:
                        print(f"[WARN] Failed to download/extract {paper.title}: {ex}")
        except Exception as e:
            print(f"[WARN] arXiv API or extraction failed: {e}")
            
        if not success:
            print("[WARN] Scraper was unable to collect arXiv papers. Loading mock papers from config_sources.yaml...")
            mock_papers = self.config.get("mock_papers", [])
            for paper in mock_papers:
                self._save_mock_paper(
                    title=paper.get("title", "Untitled Paper"),
                    paper_id=paper.get("arxiv_id", "0000.0000"),
                    date=paper.get("date", "2015-01-01"),
                    abstract=paper.get("abstract", "")
                )

    def _download_and_extract(self, pdf_url, paper_id, title, date):
        """Download PDF and extract text"""
        print(f"Downloading PDF: {title} ({pdf_url})...")
        response = requests.get(pdf_url, timeout=20)
        
        # Save to temporary file in the workspace
        tmp_dir = Path("storage/tmp")
        tmp_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = tmp_dir / f"{paper_id}.pdf"
        
        with open(pdf_path, 'wb') as f:
            f.write(response.content)
            
        # Extract text using pdfminer
        from pdfminer.high_level import extract_text
        text = extract_text(str(pdf_path))
        
        # Save text file
        output_file = f"{self.output_dir}/{paper_id}_{title.replace(' ', '_')[:50]}.txt"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# {title}\n")
            f.write(f"arXiv ID: {paper_id}\n")
            f.write(f"Date: {date.strftime('%Y-%m-%d') if hasattr(date, 'strftime') else date}\n")
            f.write(f"URL: https://arxiv.org/abs/{paper_id}\n\n")
            f.write(text)
            
        print(f"[OK] Extracted text from paper: {title}")
        # Cleanup
        os.remove(pdf_path)

    def _save_mock_paper(self, title, paper_id, date, abstract):
        """Save a mock paper document"""
        output_file = f"{self.output_dir}/{paper_id}_{title.replace(' ', '_')[:50]}.txt"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# {title}\n")
            f.write(f"arXiv ID: {paper_id}\n")
            f.write(f"Date: {date}\n")
            f.write(f"URL: https://arxiv.org/abs/{paper_id}\n\n")
            f.write(f"Abstract: {abstract}\n\n")
            f.write("Full Text (Mocked):\n")
            f.write(f"In this paper, we explore the deep alignments between visual and semantic features. ")
            f.write("Specifically, we show that visual embeddings generated by deep Convolutional Neural Networks (CNNs) ")
            f.write("can be mapped directly into semantic spaces generated by Recurrent Neural Networks (RNNs) for image description. ")
            f.write("We evaluate our approach on ImageNet and Flickr datasets, showing significant improvements over state of the art models.")
        print(f"[OK] Saved mock paper: {title}")

if __name__ == "__main__":
    PaperCollector().collect()
